


DELETE FROM SQUARK_STAGING.ADVSR WHERE (ADVSR_SID,_advana_md5) in (select ADVSR_SID,_advana_md5 from TERADATA_SIERA.ADVSR);
COMMIT;

DELETE FROM TERADATA_SIERA.ADVSR WHERE (ADVSR_SID) in ( select ADVSR_SID from SQUARK_STAGING.ADVSR );

INSERT INTO TERADATA_SIERA.ADVSR
SELECT * FROM SQUARK_STAGING.ADVSR ;
COMMIT;
