


DELETE FROM SQUARK_STAGING.AGMT WHERE (AGMT_SID,_advana_md5) in (select AGMT_SID,_advana_md5 from TERADATA_SIERA.AGMT);
COMMIT;

DELETE FROM TERADATA_SIERA.AGMT WHERE (AGMT_SID) in ( select AGMT_SID from SQUARK_STAGING.AGMT );

INSERT INTO TERADATA_SIERA.AGMT
SELECT * FROM SQUARK_STAGING.AGMT ;
COMMIT;
