


DELETE FROM SQUARK_STAGING.AGMT WHERE (AGMT_SID,_advana_md5) in (select AGMT_SID,_advana_md5 from dmd_test.AGMT);
COMMIT;

DELETE FROM DMD_TEST.AGMT WHERE (AGMT_SID) in ( select AGMT_SID from SQUARK_STAGING.AGMT );

INSERT INTO DMD_TEST.AGMT
SELECT * FROM SQUARK_STAGING.AGMT ;
COMMIT;
