--- clear out TERADATA_SIERA.CAL_VW
TRUNCATE TABLE TERADATA_SIERA.CAL_VW;

--- insert the replacement records
INSERT INTO TERADATA_SIERA.CAL_VW
SELECT * FROM SQUARK_STAGING.teradata_siera_cal_vw ;
COMMIT;
