


DELETE FROM SQUARK_STAGING.COMM_FACT WHERE (COMM_TXN_ID,_advana_md5) in (select COMM_TXN_ID,_advana_md5 from dmd_test.COMM_FACT);
COMMIT;

DELETE FROM DMD_TEST.COMM_FACT WHERE (COMM_TXN_ID) in ( select COMM_TXN_ID from SQUARK_STAGING.COMM_FACT );

INSERT INTO DMD_TEST.COMM_FACT
SELECT * FROM SQUARK_STAGING.COMM_FACT ;
COMMIT;
