


DELETE FROM SQUARK_STAGING.PREMIUM_FACT WHERE (PREM_TXN_ID,_advana_md5) in (select PREM_TXN_ID,_advana_md5 from TERADATA_SIERA.PREMIUM_FACT);
COMMIT;

DELETE FROM TERADATA_SIERA.PREMIUM_FACT WHERE (PREM_TXN_ID) in ( select PREM_TXN_ID from SQUARK_STAGING.PREMIUM_FACT );

INSERT INTO TERADATA_SIERA.PREMIUM_FACT
SELECT * FROM SQUARK_STAGING.PREMIUM_FACT ;
COMMIT;
