


DELETE FROM SQUARK_STAGING.PREMIUM_FACT WHERE (PREM_TXN_ID,_advana_md5) in (select PREM_TXN_ID,_advana_md5 from dmd_test.PREMIUM_FACT);
COMMIT;

DELETE FROM DMD_TEST.PREMIUM_FACT WHERE (PREM_TXN_ID) in ( select PREM_TXN_ID from SQUARK_STAGING.PREMIUM_FACT );

INSERT INTO DMD_TEST.PREMIUM_FACT
SELECT * FROM SQUARK_STAGING.PREMIUM_FACT ;
COMMIT;
