


DELETE FROM SQUARK_STAGING.PROD WHERE (PROD_SID,_advana_md5) in (select PROD_SID,_advana_md5 from dmd_test.PROD);
COMMIT;

DELETE FROM DMD_TEST.PROD WHERE (PROD_SID) in ( select PROD_SID from SQUARK_STAGING.PROD );

INSERT INTO DMD_TEST.PROD
SELECT * FROM SQUARK_STAGING.PROD ;
COMMIT;
