


DELETE FROM SQUARK_STAGING.PROD WHERE (PROD_SID,_advana_md5) in (select PROD_SID,_advana_md5 from TERADATA_SIERA.PROD);
COMMIT;

DELETE FROM TERADATA_SIERA.PROD WHERE (PROD_SID) in ( select PROD_SID from SQUARK_STAGING.PROD );

INSERT INTO TERADATA_SIERA.PROD
SELECT * FROM SQUARK_STAGING.PROD ;
COMMIT;
