--- clear out TERADATA_SIERA.SLS_RPTG_PREM_HIST_VW
TRUNCATE TABLE TERADATA_SIERA.SLS_RPTG_PREM_HIST_VW;

--- insert the replacement records
INSERT INTO TERADATA_SIERA.SLS_RPTG_PREM_HIST_VW
SELECT * FROM SQUARK_STAGING.teradata_siera_sls_rptg_prem_hist_vw ;
COMMIT;
