 

 TRUNCATE TABLE squark_staging.CUST_DEMOGRAPHICS_VW
; TRUNCATE TABLE squark_staging.AGMT_ADDL_DATA_VW
; TRUNCATE TABLE squark_staging.AGMT_CMN_VW
; TRUNCATE TABLE squark_staging.AGMT_CVG_CMN_VW
; TRUNCATE TABLE squark_staging.AGMT_FND_CMN_VW
; TRUNCATE TABLE squark_staging.SLLNG_AGMT_CMN_VW
; TRUNCATE TABLE squark_staging.PDCR_DEMOGRAPHICS_VW
; TRUNCATE TABLE squark_staging.PDCR_AGMT_CMN_VW
; TRUNCATE TABLE squark_staging.FUND_CMN_VW
; TRUNCATE TABLE squark_staging.CUST_AGMT_CMN_VW
; TRUNCATE TABLE squark_staging.BP_CREDENTIAL_VW
; TRUNCATE TABLE squark_staging.BENE_DATA_CMN_VW
; TRUNCATE TABLE squark_staging.AGMT_WARNING_INFO_CMN_VW
; TRUNCATE TABLE squark_staging.AGMT_VAL_CMN_VW
; TRUNCATE TABLE squark_staging.AGMT_UWRT_CMN_VW
; TRUNCATE TABLE squark_staging.AGMT_LOAN_CMN_VW
; TRUNCATE TABLE squark_staging.AGMT_GRP_CMN_VW
; TRUNCATE TABLE squark_staging.AGMT_FND_VAL_CMN_VW
;