
TRUNCATE TABLE squark_staging.LAB_RESULTS;
TRUNCATE TABLE squark_staging.LAB_DEMOGRAPHICS;
TRUNCATE TABLE squark_staging.LAB_STANDARDS;
TRUNCATE TABLE squark_staging.NAME;
TRUNCATE TABLE squark_staging.POLICY_EVENTS;
TRUNCATE TABLE squark_staging.SUMMARY;

