export PROJECT_ID=drc
export WAREHOUSE_DIR='/_wh/'
export SQL_TEMPLATE='%s'
export INCLUDE_VIEWS=1
#export INCLUDE_TABLES='AGMT_CMN_VW,CUST_AGMT_CMN_VW,CUST_DEMOGRAPHICS_VW,PDCR_AGMT_CMN_VW,PDCR_DEMOGRAPHICS_VW,AGMT_UWRT_CMN_VW,PDCR_ALT_ID_CMN_VW,CUST_PREFERENCE_VW,SLLNG_AGMT_CMN_VW,AGMT_VAL_CMN_VW,AGMT_CVG_CMN_VW,BP_CREDENTIAL_VW'
export EXCLUDE_TABLES='BI_NFF_FACT_VW,BI_SLS_DISB_FACT_VW'
export CONNECTION_ID=drc

export SPARK_MAX_EXECUTORS=15

