export PROJECT_ID=reflex_work
export WAREHOUSE_DIR='/_wh/'
export SQL_TEMPLATE='%s'
#export EXCLUDE_TABLES="CMB_PARTC_TOT_MILESTONE_WORK,DB_RPT_REQUEST_TRACKING_WORK"
#export INCLUDE_TABLES="LOAN_DLLOG_V,LOAN_PIT_DLLOG_V,R1099_DATA_DLLOG_V,TXN_GROUP_DETAIL_DLLOG_V,FUND_DLLOG_V,SOURCE_DLLOG_V,BENEFICIARY_DLLOG_V,CENSUS_DLLOG_V,CENSUS_EE_DLLOG_V,MEMBER_PIT_DLLOG_V,MEMBER_STATUS_HISTORY_DLLOG_V,MEMBERS_DLLOG_V,PARTC_CALC_VESTED_BAL_DLLOG_V,PARTICIPANT_DLLOG_V,PERSON_DLLOG_V,PLAN_FORM_HIST_DLLOG_V,PROVIDER_DLLOG_V,BUSINESS_ENTITY_DLLOG_V,SUBSCRIPTION_SOURCE_DLLOG_V,CONTACT_DLLOG_V,FUND_MSTR_DLLOG_V,EXTERNAL_ADDRESS_DLLOG_V,INV_CONTRACT_DLLOG_V,PLAN_DCO_DLLOG_V,PLAN_FUND_DLLOG_V,PLAN_SOURCE_DLLOG_V,PLAN_SPONSOR_DLLOG_V,PLAN_SUBSCRIPTION_DLLOG_V,SUBSCRIPTION_FUND_DLLOG_V,ACTIVITY_DLLOG_V,APPLICATION_IDENTIFICATION_DLLOG_V,ACCOUNT_REG,PARTC_REG,TXN_HEADER"
export INCLUDE_TABLES="LOAN_DLLOG,LOAN_PIT_DLLOG,R1099_DATA_DLLOG,TXN_GROUP_DETAIL_DLLOG,FUND_DLLOG,SOURCE_DLLOG,BENEFICIARY_DLLOG,CENSUS_DLLOG,CENSUS_EE_DLLOG,MEMBER_PIT_DLLOG,MEMBER_STATUS_HISTORY_DLLOG,MEMBERS_DLLOG,PARTC_CALC_VESTED_BAL_DLLOG,PARTICIPANT_DLLOG,PERSON_DLLOG,PLAN_FORM_HIST_DLLOG,PROVIDER_DLLOG,BUSINESS_ENTITY_DLLOG,SUBSCRIPTION_SOURCE_DLLOG,CONTACT_DLLOG,FUND_MSTR_DLLOG,EXTERNAL_ADDRESS_DLLOG,INV_CONTRACT_DLLOG,PLAN_DCO_DLLOG,PLAN_FUND_DLLOG,PLAN_SOURCE_DLLOG,PLAN_SPONSOR_DLLOG,PLAN_SUBSCRIPTION_DLLOG,SUBSCRIPTION_FUND_DLLOG,ACTIVITY_DLLOG,APPLICATION_IDENTIFICATION_DLLOG,ACCOUNT_REG,PARTC_REG,TXN_HEADER"
export INCLUDE_VIEWS=1
export CONNECTION_ID=reflex_datalake
#export STATS_CONFIG="
#{
#    'profiles': {
#        'numeric': ['max','min','mean','countDistinct','count_null'],
#        'string': ['max', 'min','countDistinct','count_null'],
#        'datetype': ['max', 'min','countDistinct','count_null']
#    },
#    'field_types': {
#        'NumericType': 'numeric',
#        'StringType': 'string',
#        'DateType': 'datetype',
#        'TimestampType': 'datetype'
#    }
#}
#"
