export PROJECT_ID=teradata_cmn
export WAREHOUSE_DIR='/_wh/'
export SQL_TEMPLATE='%s'
export INCLUDE_VIEWS=1
export CONNECTION_ID=teradata_cmn

INCLUDE_TABLES_ARRAY=(
  "AGMT_STUS_CD_LKUP"
  "AGMT_STUS_RSN_CD_LKUP_VW"
  "AGY_CLOSE_MERGE_DATA_VW"
  "COMM_DT_VW"
  "DSTRB_CHNL_CD_VW"
  "DTH_CD_LKUP_VW"
  "GENDER_CD_VW"
  "GOVT_ID_TYPE"
  "GOVT_ID_TYP_VW"
  "MET_AGT_POINTINTIME_VW"
  "MKT_INFO_CD_VW"
  "MKT_TYP_CD_LKUP_VW"
  "PRODUCT_TRANSLATOR_VW"
  "PRTY_RLE_TYP_CD_LKUP_VW"
  "PRTY_TYP_VW"
  "RCOG_PROD_VW"
  "SLS_DTRB_CAL_VW"
  "SRC_DATA_TRNSLT_VW"
)

export INCLUDE_TABLES="$(IFS=, ; echo "${INCLUDE_TABLES_ARRAY[*]}")"

