export PROJECT_ID=teradata_prod_dma
export WAREHOUSE_DIR='/_wh/'
export SQL_TEMPLATE='%s'
export INCLUDE_VIEWS=1
export INCLUDE_TABLES='ACTIVITY_FCT_REJECT_VW,ACTIVITY_FCT_VW,ACTIVITY_TO_FCT_VW,ACTIVITY_WGT_FCT_VW,ACT_DIBS_DIARY_FCT_VW,ACT_DIBS_PAYMENT_FCT_VW,ACT_DIC_CURR_INTEGRATED_VW,ACT_DIC_INTEGRATED_FCT_VW,ACT_DIC_PIT_INTEGRATED_VW,ACT_GM4PAYMENT_FCT_VW,ACT_MEDVOC_FCT_VW,ACT_TREX_CONTENT_FCT_VW,ACT_TREX_WORK_FCT_VW,ADMN_SYS_CDE_LOV_VW,ASSIGNED_TO_TREX_IOT_VW,CURR_PEND_VW,DATE_DIM_VW,DBO_AGENT_VW,DBO_BILLING_VW,DBO_CONTENT_VW,DBO_CONTRACT_VW,DBO_COVERAGE_VW,DBO_DIBS_CLAIM_STATUS_VW,DBO_DIBS_CLAIM_VW,DBO_DIBS_CUSTOMER_VW,DBO_DIBS_DIARY_VW,DBO_DIBS_ICD_VW,DBO_DIBS_PAYEE_VW,DBO_DIBS_PAYMENT_TRAN_VW,DBO_DIBS_POLICY_VW,DBO_DIV_VW,DBO_EXCLUSIONS_VW,DBO_FA_HISTORY_VW,DBO_GROUP_INFO_VW,DBO_HRFEED_VW,DBO_IM_COVERAGE_INFO_VW,DBO_INBASKET_EXT_VW,DBO_INBASKET_STATUS_VW,DBO_INSURED_VW,DBO_IPN_NAME_VW,DBO_MEDVOC_BH_VW,DBO_MEDVOC_MEDORTHO_VW,DBO_MEDVOC_VOC_VW,DBO_NIGO_RSN_VW,DBO_REQUIREMENTS_ALL_VW,DBO_SVC_CHNL_CDE_VW,DBO_TCASE_BUS_PRCS_ALL_VW,DBO_TCM_BUS_PRCS_VW,DBO_TREX_USERS_VW,DBO_TREX_WORKFLOW_VW,DBO_USR_PROC_VW,DBO_WOB_TIME_SERIES_TOKEN_VW,DBO_WOB_TIME_SERIES_VW,DBO_WORK_OBJECT_STEPS_VW,DBO_WORK_OBJECT_TOKEN_VW,DBO_WORK_OBJECT_VW,DBO_WRK_XTN_VW,DEPARTMENT_LOV_VW,DIARY_CODE_LOV_VW,DIC_RISK_INVENTORY_FCT_VW,DIC_RISK_INVENTORY_RPT_VW,DIC_RISK_TYPE_VW,DI_CLAIM_CURR_DIM_VW,DI_CLAIM_DIM_VW,EMPLOYEE_CURR_DIM_VW,EMPLOYEE_PIT_DIM_VW,FACT_TABLE_LOV_VW,FUNCTION_LOV_VW,GOAL_DIM_VW,GROUP_LOV_VW,GROUP_TYPE_LOV,ICD_GROUP_IOT_VW,ICD_GROUP_LOV_VW,JOB_LOG_QA_VW,JOB_LOV_VW,ORGANIZATION_LOV_VW,PARTY_EMPLOYEE_VW,PARTY_TEAM_IOT_VW,PARTY_TYPE_LOV_VW,PRIMARY_LOG_LOV_VW,PRIORITY_LOV_VW,PROCESS_IOT_VW,PROCESS_LOV_VW,PSC_MART_CURR_IVW,PSC_MART_PIT_IVW,PSC_MART_VW,REFERRAL_TRANSFER_FCT_VW,ROLE_IOT_VW,ROLE_LOV_VW,SCHEDULE_DIM_VW,SCHEDULE_VW,SEGMENT_LOV_VW,SITE_LOV_VW,STATUS_CODE_LOV_VW,SYSTEM_DIV_DEPARTMENT_VW,SYSTEM_LOV_VW,TASK_LOV_VW,TEAM_FUNCTION_LOV_VW,TEAM_TYPE_LOV_VW,TEAM_VW,TIMEOUT_ACTIVITY_CURR_IVW,TIMEOUT_ACTIVITY_PIT_IVW,TIME_ACTIVITY_CURR_IVW,TIME_ACTIVITY_PIT_IVW,TIME_ACTIVITY_PROD_VW,TIME_ACTIVITY_VW,TIME_CATEGORIES_VW,TIME_FCT_VW,TIME_TYPE_VW,TRANSACTION_TYPE_LOV_VW,TRANS_CURR_INTEGRATED_PVW,TRANS_CURR_INTEGRATED_VW,TRANS_PIT_INTEGRATED_PVW,TRANS_PIT_INTEGRATED_VW,WORK_EVENT_CURR_DIM_VW,WORK_EVENT_PIT_DIM_VW,WORK_EVENT_VW,WORK_IOT_VW'
export CONNECTION_ID=teradata_prod_dma

export SPARK_MAX_EXECUTORS=10
export JSON_INFO='{
	"PARTITION_INFO": {
		"tables": {
			"ACTIVITY_FCT_VW": {
				"partitionColumn": "SourceTransactionID",
				"lowerBound": 5050000000,
				"upperBound": 5099339861,
				"numPartitions": 100
			},
            "ACT_DIC_CURR_INTEGRATED_VW": {
				"partitionColumn": "IntegratedActivityID",
				"lowerBound": 10000000,
				"upperBound": 163048206,
				"numPartitions": 100
			},
            "ACT_DIC_INTEGRATED_FCT_VW": {
				"partitionColumn": "IntegratedActivityID",
				"lowerBound": 10000000,
				"upperBound": 163048206,
				"numPartitions": 100
			},
			"ACT_DIC_PIT_INTEGRATED_VW": {
				"partitionColumn": "IntegratedActivityID",
				"lowerBound": 10000000,
				"upperBound": 163048206,
				"numPartitions": 100
			},
			"DBO_REQUIREMENTS_ALL_VW": {
				"partitionColumn": "CaseId",
				"lowerBound": 1,
				"upperBound": 12000000,
				"numPartitions": 20
			},
			"DBO_TCASE_BUS_PRCS_ALL_VW": {
				"partitionColumn": "CaseId",
				"lowerBound": 1,
				"upperBound": 40000000,
				"numPartitions": 20
			},
			"ACT_TREX_WORK_FCT_VW": {
				"partitionColumn": "ActivityID",
				"lowerBound": 100000,
				"upperBound": 5000000,
				"numPartitions": 25
			}
		}
	}
}'