export PROJECT_ID=verint
export WAREHOUSE_DIR='/_wh/'
export SQL_TEMPLATE='%s'
export INCLUDE_TABLES="CAMPAIGN,FORECASTINSTANCE,FORECASTTIMESERIES,PREDICTEDTIMESERIES,QUEUE,SKILL,SP,SPQUEUE,SPQUEUEGOALSERIES,SPQUEUESKILL"
export CONNECTION_ID=verint
export SQUARK_METADATA=1