export PROJECT_ID=verint
export WAREHOUSE_DIR='/_wh/'
export SQL_TEMPLATE='%s'
# 2017.10.31, leaving out QUEUEHISTORYTIMESERIES until filter/partitioning is figured out
export INCLUDE_TABLES="CAMPAIGN,FORECASTINSTANCE,FORECASTTIMESERIES,QUEUE,SKILL,SP,SPQUEUESKILL,SPQUEUE,SPQUEUEGOALSERIES"
export CONNECTION_ID=verint
export SQUARK_METADATA=1