here="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export SQUARK_LOG_LEVEL=INFO
#export SQUARK_CONFIG_DIR="$here/config"
#export SQUARK_PASSWORD_FILE="$here/.squark-password"
#export SPARK_LOCAL_DIR=/hadoop/sparklocal
export HADOOP_USER_NAME=jenkins
#export SPARK_HOME=/hadoop/spark/1.6
export PYTHONPATH="$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.9-src.zip:$PYTHONPATH"
#export HADOOP_CONF_DIR=/etc/hadoop/conf
#export CLASSPATH="/hdfs/deploy/jdbc/py4jdbc-assembly-latest.jar"
export CLASSPATH="$here/.jars/py4jdbc-assembly-latest.jar:$here/.jars/sqljdbc41.jar:$CLASSPATH"
export PATH="$PATH:$PWD/scripts"
export VAULT_PASSWORD_FILE="$SQUARK_PASSWORD_FILE"
