-- Get rid of the current haven_uw_interaction_backup table
DROP TABLE IF EXISTS SQUARK_STAGING.HAVEN_INTERACTION_BACKUP;

-- Replace it with the current table in haven
SELECT COPY_TABLE('HAVEN.INTERACTION', 'SQUARK_STAGING.HAVEN_INTERACTION_BACKUP');
GRANT ALL  PRIVILEGES  EXTEND  ON TABLE SQUARK_STAGING.HAVEN_INTERACTION_BACKUP  TO  SQUARK_STAGING_ADMIN;
