-- Get rid of the current HAVEN_INTERACTION_INCR table
DROP TABLE IF EXISTS SQUARK_STAGING.HAVEN_INTERACTION_INCR;

-- And re-create it
CREATE TABLE IF NOT EXISTS SQUARK_STAGING.HAVEN_INTERACTION_INCR LIKE HAVEN.INTERACTION INCLUDING PROJECTIONS INCLUDE PRIVILEGES;

-- Grants
GRANT ALL  PRIVILEGES  EXTEND  ON TABLE squark_staging.HAVEN_INTERACTION_INCR  TO  squark_staging_admin;
