



DELETE FROM DMD_TEST.AGMT_UWRT_CMN_VW WHERE (agreement_id) in ( select agreement_id from SQUARK_STAGING.AGMT_UWRT_CMN_VW );

INSERT INTO DMD_TEST.AGMT_UWRT_CMN_VW
SELECT * FROM SQUARK_STAGING.AGMT_UWRT_CMN_VW ;
COMMIT;
