




DELETE FROM DMD_TEST.AGMT_LOAN_CMN_VW WHERE (AGREEMENT_ID, AGREEMENT_SOURCE_CD ,HLDG_KEY_PFX ,HLDG_KEY ,HLDG_KEY_SFX) in ( select agreement_id, AGREEMENT_SOURCE_CD ,HLDG_KEY_PFX ,HLDG_KEY ,HLDG_KEY_SFX from SQUARK_STAGING.AGMT_LOAN_CMN_VW );

INSERT INTO DMD_TEST.AGMT_LOAN_CMN_VW
SELECT * FROM SQUARK_STAGING.AGMT_LOAN_CMN_VW ;
COMMIT;