


DELETE FROM DMD_TEST.AGMT_ADDL_DATA_VW WHERE (agreement_id) in ( select agreement_id from SQUARK_STAGING.AGMT_ADDL_DATA_VW );

INSERT INTO DMD_TEST.AGMT_ADDL_DATA_VW
SELECT * FROM SQUARK_STAGING.AGMT_ADDL_DATA_VW ;
COMMIT;
