




DELETE FROM DMD_TEST.BENE_DATA_CMN_VW WHERE (AGREEMENT_ID,AGREEMENT_SOURCE_CD,HLDG_KEY_PFX,HLDG_KEY,HLDG_KEY_SFX) in ( select HIST_AGREEMENT_ID,
 HIST_AGREEMENT_SOURCE_CD,
 HIST_HLDG_KEY_PFX,
 HIST_HLDG_KEY,
 HIST_HLDG_KEY_SFX from SQUARK_STAGING.BENE_DATA_CMN_VW WHERE AGREEMENT_ID IS NULL );

DELETE FROM DMD_TEST.BENE_DATA_CMN_VW WHERE (AGREEMENT_ID,AGREEMENT_SOURCE_CD,HLDG_KEY_PFX,HLDG_KEY,HLDG_KEY_SFX) in ( select AGREEMENT_ID,AGREEMENT_SOURCE_CD,HLDG_KEY_PFX,HLDG_KEY,HLDG_KEY_SFX from SQUARK_STAGING.BENE_DATA_CMN_VW WHERE AGREEMENT_ID IS NOT NULL);

INSERT INTO DMD_TEST.BENE_DATA_CMN_VW
SELECT 
AGREEMENT_ID,
 BENE_ROLE_CD,
 BENE_ROLE_POSITION_CD,
 SRC_RLE_CD,
 SRC_BENE_ROLE_POSITION_CD,
 BENE_ROLE_SEQ_NO,
 SRC_RLE_SEQ_NBR,
 BENE_DATA_FR_DT,
 BENE_DATA_TO_DT,
 AGREEMENT_SOURCE_CD,
 HLDG_KEY_PFX,
 HLDG_KEY,
 HLDG_KEY_SFX,
 BENE_GNDR_CD,
 BENE_BRTH_DT,
 BENE_GOVT_ID_TYP,
 BENE_GOVT_ID,
 BENE_NM_TYP_CD,
 BENE_FULL_NM,
 BENE_PFX_NM,
 BENE_FRST_NM,
 BENE_MID_NM,
 BENE_LST_NM,
 BENE_SFX_NM,
 BENE_PROF_DSGN,
 BENEFICIARY_DESIGNATION,
 BENE_RELATIONSHIP_TYPE_CD,
 BENEFICIARY_DESIGNATED_PCT,
 BENE_EFF_DT,
 BENE_TRUST_DATE,
 BENE_CLASS_CD,
 SRC_BEN_CLS_CD,
 BENE_SPEC_DSGNTN,
 BENE_ROW_CNTR,
 AGMT_DATA_FR_DT,
 RLE_STYP_CD,
 PRTY_ID,
 MEMBER_ID,
 BENE_SUB_CLASS_CD,
 BENE_TYP_CD,
 BENEFICIARY_DESIGNATED_AMT,
 BENE_ISS_PER_STIRPES_CD,
 _advana_md5,
 _advana_id,
 _advana_load_date
  FROM SQUARK_STAGING.BENE_DATA_CMN_VW 
  WHERE AGREEMENT_ID IS NOT NULL ;
COMMIT;
