


DELETE FROM DMD_TEST.CUST_AGMT_CMN_VW WHERE (agreement_id,PRTY_ID) in ( select HIST_agreement_id,HIST_PRTY_ID from SQUARK_STAGING.CUST_AGMT_CMN_VW WHERE AGREEMENT_ID IS NULL);
DELETE FROM DMD_TEST.CUST_AGMT_CMN_VW WHERE (agreement_id,PRTY_ID) in ( select agreement_id,PRTY_ID from SQUARK_STAGING.CUST_AGMT_CMN_VW WHERE AGREEMENT_ID IS NOT NULL);

INSERT INTO DMD_TEST.CUST_AGMT_CMN_VW
SELECT 
PRTY_ID,
 AGREEMENT_ID,
 PRTY_AGMT_FR_DT,
 PRTY_AGMT_TO_DT,
 PRTY_AGMT_RLE_CD,
 SRC_PRTY_AGMT_RLE_CD,
 PRTY_AGMT_RLE_STYP_CD,
 SRC_PRTY_AGMT_RLE_STYP_CD,
 AGMT_FR_DT,
 PRTY_DATA_FR_DT,
 HLDG_KEY_PFX,
 HLDG_KEY,
 HLDG_KEY_SFX,
 AGREEMENT_SOURCE_CD,
 MEMBER_ID,
 PRTY_AGMT_AD_FR_DT,
 PRTY_AGMT_AD_TO_DT,
 AD_TYP_CD,
 SRC_ST_AD_TYP_CD,
 ATTN_LINE,
 AD_L1_TXT,
 AD_L2_TXT,
 AD_L3_TXT,
 AD_L4_TXT,
 CITY,
 STATE,
 CTRY_CD,
 ZIP_1_5_NR,
 ZIP_6_9_NR,
 ZIP_10_13_NR,
 FULL_POST_CD,
 ADDR_VAL_CD,
 ADDR_VER_DT,
 DMST_FRGN_CD,
 TIME_ZN,
 SRC_TIME_ZN,
 SRC_STATE,
 SRC_CTRY_CD,
 PFX_NM,
 FIRST_NM,
 MID_NM,
 LST_NM,
 SFX_NM,
 FULL_NM,
 SRC_DEL_IND,
 _advana_md5,
 _advana_id,
 _advana_load_date
  FROM SQUARK_STAGING.CUST_AGMT_CMN_VW
  WHERE PRTY_ID IS NOT NULL ;
COMMIT;
