




DELETE FROM DMD_TEST.PDCR_AGMT_CMN_VW WHERE (agreement_id,PRTY_ID) in ( select HIST_agreement_id,HIST_PRTY_ID from SQUARK_STAGING.PDCR_AGMT_CMN_VW WHERE AGREEMENT_ID IS NULL);
DELETE FROM DMD_TEST.PDCR_AGMT_CMN_VW WHERE (agreement_id,PRTY_ID) in ( select agreement_id,PRTY_ID from SQUARK_STAGING.PDCR_AGMT_CMN_VW WHERE AGREEMENT_ID IS NOT NULL);
INSERT INTO DMD_TEST.PDCR_AGMT_CMN_VW
SELECT 
 PRTY_ID,
 AGREEMENT_ID,
 PRTY_AGMT_RLE_CD,
 PRTY_AGMT_RLE_STYP_CD,
 BUS_STRT_DT,
 BUS_END_DT,
 SRC_PRTY_AGMT_RLE_STYP_CD,
 SRC_PRTY_AGMT_RLE_CD,
 AGMT_FR_DT,
 PRTY_DATA_FR_DT,
 HLDG_KEY_PFX,
 HLDG_KEY,
 HLDG_KEY_SFX,
 AGREEMENT_SOURCE_CD,
 BUSINESS_PARTNER_ID,
 AGT_1ST_YR_COMM_PCT,
 AGT_COMM_SPLIT,
 AGT_RNWL_COMM_PCT,
 AGT_WRTG_AGY_PRTY_ID,
 AGT_WRTG_AGY_CD,
 AGT_WRTG_AGY_BPID,
 SRC_ALT_PRTY_ID,
 SVC_AGT_IND,
 AGT_DSPY_ORDR,
 SRC_SYS_ID,
 RUN_ID,
 UPDT_RUN_ID,
 TRANS_DT,
 AGY_DSTRB_CHNL,
 AGY_DSTRB_CHNL_DESC,
 SOLICIT_WRTG_AGT_IND,
 AGT_FIRM_BPID,
 AGT_FIRM_PRTY_ID,
 AGT_CONTR_SRC_ALT_ID,
 FIRM_CONTR_SRC_ALT_ID,
 FIRM_SLLNG_AGMT_TYP_CD,
 CAREER_CORP_IND,
 BASE_BIZPKG_ID,
 BIZPKG_STUS_CD,
 BIZPKG_STUS_RSN_CD,
 SRC_BIZPKG_STUS_CD,
 SRC_BIZPKG_STUS_RSN_CD,
 AGREEMENT_DSTRB_CHNL_CD,
 AGREEMENT_DSTRB_CHNL_DESC,
 SLLNG_AGMT_RLE_CD,
 FIRM_SLLNG_AGMT_RLE_CD,
 _advana_md5,
 _advana_id,
 _advana_load_date
  FROM SQUARK_STAGING.PDCR_AGMT_CMN_VW 
  WHERE 
  AGREEMENT_ID IS NOT NULL;

COMMIT;
