



DELETE FROM DMD_TEST.SLLNG_AGMT_CMN_VW WHERE (CONTR_ID) in ( select CONTR_ID from SQUARK_STAGING.SLLNG_AGMT_CMN_VW );

INSERT INTO DMD_TEST.SLLNG_AGMT_CMN_VW
SELECT * FROM SQUARK_STAGING.SLLNG_AGMT_CMN_VW ;
COMMIT;
