
DELETE FROM DMD_TEST.AGMT_PAC_DATA_VW WHERE (AGMT_ID, agmt_pac_data_fr_dt) in ( select AGMT_ID, agmt_pac_data_fr_dt from SQUARK_STAGING.AGMT_PAC_DATA_VW );

INSERT INTO DMD_TEST.AGMT_PAC_DATA_VW
SELECT * FROM SQUARK_STAGING.AGMT_PAC_DATA_VW ;
COMMIT;