DELETE FROM :schema_name.FNL_AGMT_HIST_VW WHERE ISSUE_DT IN (SELECT ISSUE_DT FROM :schema_name.AGMT_HIST_VW GROUP BY 1);

INSERT INTO :schema_name.FNL_AGMT_HIST_VW
SELECT * FROM :schema_name.AGMT_HIST_VW;

COMMIT;