echo "launch_squark_job.sh USAGE:"
echo "  ./launch_squark_job.sh [[-v=*] [-w=*]] [-h] [[--dev|--prod]] <job_name>"
echo "This script will launch a squark job. The default behaviour is to launch a dev job."
echo "MAKE SURE to include the job name so the script knows which file to source."
echo "Default values are:"
echo "If you want to run a prod job, just include --prod or --production as an argument."
echo "The script also accepts --dev or --develop to run a dev job."
echo "The below options can be used to override the default dev and prod variables if needed."
echo "However, you cannot override and select an environment (dev|qa|prod). The last value will always trump the first ones."
echo "OPTIONS:"
echo " -v | --vertica-id     : Override the default vertica_connection_id with value passed."
echo " -w | --warehouse-dir  : Override the default warehouse_dir with the value passed."
echo " --dev | --develop     : Set default values for a dev job."
echo " --prod | --production : Set default values for a prod job."
echo " --skip-hdfs-load      : Skip the loading of the data into hdfs."
echo " --skip-vertica-load   : Skip the loading of the data into vertica."
echo " --use-aws             : Save data to aws s3."
echo " --use-hdfs            : Save data to HDFS (if neither use-aws or use-hdfs is supplied, this is default)."
echo " --load-from-aws       : Load data from aws s3 into aws vertica."
echo " --load-from-hdfs      : Load data from HDFS into onprem vertica."
echo " --force-cutover       : The wh_cutover will only happen if a full run occurs, or this flag is specified."
echo " --make_ddl_from_target: Create the temp table from the Target Table DDL (saves projections)"
exit 0
