-- Get rid of the current haven_uw_interaction_backup table
DROP TABLE IF EXISTS SQUARK_STAGING.HAVEN_UW_INTERACTION_BACKUP;

-- Replace it with the current table in haven_uw
SELECT COPY_TABLE('HAVEN_UW.INTERACTION', 'SQUARK_STAGING.HAVEN_UW_INTERACTION_BACKUP');
GRANT ALL  PRIVILEGES  EXTEND  ON TABLE SQUARK_STAGING.HAVEN_UW_INTERACTION_BACKUP  TO  squark_staging_admin;
