--- remove records from backup table that are in this incremental batch
DELETE FROM
    SQUARK_STAGING.HAVEN_UW_INTERACTION_BACKUP
WHERE
    _ID IN (SELECT _ID FROM SQUARK_STAGING.HAVEN_UW_INTERACTION_INCR);

--- add batch to backup table
INSERT INTO
    SQUARK_STAGING.HAVEN_UW_INTERACTION_BACKUP
SELECT
    *
FROM
    SQUARK_STAGING.HAVEN_UW_INTERACTION_INCR;

COMMIT;
