

DELETE FROM DMD_TEST.PRTY_ALT_ID_VW WHERE (PRTY_ID,ALT_ID,PRTY_ALT_ID_FR_DT) in ( select PRTY_ID,ALT_ID,PRTY_ALT_ID_FR_DT from SQUARK_STAGING.PRTY_ALT_ID_VW );

INSERT INTO DMD_TEST.PRTY_ALT_ID_VW
SELECT * FROM SQUARK_STAGING.PRTY_ALT_ID_VW ;
COMMIT;