truncate table prod_stnd_crcog_tbls.SEC_COMP_ADJ ;

INSERT
INTO
    prod_stnd_crcog_tbls.SEC_COMP_ADJ
    (
        PRTY_ID,
        BP_ID,
        AGY_ID,
        AGY_NR,
        SECONDARY_BPID,
        SEC_COMP_CAT_TYPE_CD,
        SEC_COMP_TYP_CD,
        SRC_SEC_COMP_TYP_CD,
        PAY_SYS_CYCLE_DT,
        PAY_SYS_ACK_DT,
        TRILOGY_ID,
        SEC_COMP_ADJ_DT,
        SEC_COMP_ADJ_AMT,
        SEC_COM_ADJ_RSN_DESC,
        PROD_TYP_CD,
        DTCHD_OFC_ID,
        CO_CD,
        PAY_SYS_ACK_IND,
        COMP_CALC_MDL_CD,
        NASD_CD,
        UNIT_BP_ID,
        UNIT_NR,
        SRC_HLDG_KEY,
        AGREEMENT_ID,
        CARR_ADMIN_SYS_CD,
        HLDG_KEY,
        HLDG_KEY_PFX,
        HLDG_KEY_SFX,
        SRC_SYS_ID,
        RUN_ID,
        UPDT_RUN_ID,
        TRANS_DT,
        SRC_DEL_IND,
        CURR_IND
    )
    select PRTY_ID,
        BP_ID,
        AGY_ID,
        AGY_NR,
        SECONDARY_BPID,
        SEC_COMP_CAT_TYPE_CD,
        SEC_COMP_TYP_CD,
        SRC_SEC_COMP_TYP_CD,
        PAY_SYS_CYCLE_DT,
        PAY_SYS_ACK_DT,
        TRILOGY_ID,
        SEC_COMP_ADJ_DT,
        SEC_COMP_ADJ_AMT,
        SEC_COM_ADJ_RSN_DESC,
        PROD_TYP_CD,
        DTCHD_OFC_ID,
        CO_CD,
        PAY_SYS_ACK_IND,
        COMP_CALC_MDL_CD,
        NASD_CD,
        UNIT_BP_ID,
        UNIT_NR,
        SRC_HLDG_KEY,
        AGREEMENT_ID,
        CARR_ADMIN_SYS_CD,
        HLDG_KEY,
        HLDG_KEY_PFX,
        HLDG_KEY_SFX,
        SRC_SYS_ID,
        RUN_ID,
        UPDT_RUN_ID,
        TRANS_DT,
        SRC_DEL_IND,
        CURR_IND from squark_staging.SEC_COMP_ADJ_VW;


commit ;
